### ISSUE TITLE
access logs are piling up continuously

### ISSUE THREAD

**Issue by whitedba** [toni-moreno/influxdb-srelay#23]
Hello, I'm testing with RPM installed.
but, access logs are piling up continuously.

https://github.com/toni-moreno/influxdb-srelay/blob/0dab7079b642d9ad11e963c218480c2ee425d936/relay/http.go#L76

I wonder if there is any way to adjust the log_level or stack the access log gently.

**Comment by toni-moreno** [comment]
Hi @whitedba , there are two log types:

# Access Log

These logs give info about all incoming requests, and (right now) there is no way to filter them, its main goal is to have a way to review processing time for each request and the "traceroute".

I suggest to use logrotate and place logs on a different FS ( currently we are doing rotation on each hour on a 20G FS with only 7 history files).

If you need another way to count access.log please open a feature request, with your desired filtering proposal.

# Routing/Transformation logs

These logs give us info about how influxdb-srelay is working with incoming request, could be configured to different log levels and data shown depends on the object type , these are the 3 objects with logs

* Cluster logs

https://github.com/toni-moreno/influxdb-srelay/blob/0dab7079b642d9ad11e963c218480c2ee425d936/examples/sample.influxdb-srelay.conf#L35-L38

*  Endpoint Log

https://github.com/toni-moreno/influxdb-srelay/blob/0dab7079b642d9ad11e963c218480c2ee425d936/examples/sample.influxdb-srelay.conf#L80-L81

*  Route Log

This log could be delegated to its related endpoint

https://github.com/toni-moreno/influxdb-srelay/blob/0dab7079b642d9ad11e963c218480c2ee425d936/examples/sample.influxdb-srelay.conf#L126-L128

**Comment by whitedba** [comment]
@toni-moreno 
Thank you for your answer.

This is an environment in which more than 100 http calls occur every second.

1. The file specified in access-log will become too large.
2. If access-log is not specified, it is stored in **/var/log/message and becomes too large.**

Inevitably, there is no way to turn access-log off, so I set it to /dev/null.

The influuxdb-slay.conf is as follows:

cat /etc/influxdb-srelay/influxdb-srelay.conf

[[influxcluster]]
  name  = "ha_cluster"
  members = ["influxdb01","influxdb02"] 
  log-file = "ha_cluster.log"
  log-level = "warn"
  type = "HA"
  rate-limit = 1000000
  burst-limit =  2000000

[[http]]
  name = "http_influxdb_srelay"
  bind-addr = "0.0.0.0:9096"
  log-file = "http_influxdb_srelay_9096.log"
  log-level = "warn"
  **#access-log = "access.log"
  access-log = "/dev/null"**
  rate-limit = 1000000
  burst-limit = 2000000

..............
