### ISSUE TITLE
Add DROP SERIES in admin endpoint

### ISSUE THREAD

**Issue by jcdauchy-moodys** [toni-moreno/influxdb-srelay#34]
I am trying to DROP SERIES using the default endpoint, it results as my SERIES being dropped only on one of the influxdb instances.

I don't know how to proceed to DROP SERIES as we need to provide a "database" name and all verbs in admin endpoints do not need any database.

Would you have any solutions (except opening some ingress on each instance).

Thanks

**Comment by toni-moreno** [comment]
Did you test with the admin endpoint ? (https://github.com/toni-moreno/influxdb-srelay#adminclusterid)

The query with `curl` should be something like that

```
curl -i  -XPOST -u my_admin_user:my_admin_password http://<your_relay_enpoint>/admin/<your_cluster>  --data-urlencode "db=mydb"  --data-urlencode "q=DROP SERIES FROM "my_measurement" WHERE XXXX
```

let me know the output from the above query.

**Comment by jcdauchy-moodys** [comment]
Thanks toni for the quick answer, I didn't know I can provide the databse in the call. So it works ! 

```
{
  "Msg": "Cluster cluster_influxdb : Admin Action  db=telegraf_db&q=DROP%20SERIES%20FROM..... OK",
  "Responses": [
    {
      "Body": "{\"results\":[{\"statement_id\":0}]}\n",
      "Serverid": "influxdb-0",
      "Clusterid": "cluster_influxdb",
      "Location": "http://influxdb-0.influxdb-headless.monitoring.svc.cluster.local:8086/",
      "ContentType": "application/json",
      "ContentEncoding": "",
      "StatusCode": 200
    },
    {
      "Body": "{\"results\":[{\"statement_id\":0}]}\n",
      "Serverid": "influxdb-1",
      "Clusterid": "cluster_influxdb",
      "Location": "http://influxdb-1.influxdb-headless.monitoring.svc.cluster.local:8086/",
      "ContentType": "application/json",
      "ContentEncoding": "",
      "StatusCode": 200
    }
  ]
}
```

**Comment by jcdauchy-moodys** [comment]
Here is small snippet of python using "requests" if someone wants to DROP SERIES using srelay admin endpoint.

`
    def srelay_delete_series(self, database=None, measurement=None, tags=None):
        """Delete series from a database using srelay admin endpoint.

        Series must be filtered by either measurement and tags.
        This method cannot be used to delete all series, use
        `drop_database` instead.

        :param database: the database from which the series should be
            deleted, defaults to client's current database
        :type database: str
        :param measurement: Delete all series from a measurement
        :type measurement: str
        :param tags: Delete all series that match given tags
        :type tags: dict
        """
        database = database or self._database
        query_str = 'DROP SERIES'
        if measurement:
            query_str += ' FROM {0}'.format(quote_ident(measurement))

        if tags:
            tag_eq_list = ["{0}={1}".format(quote_ident(k), quote_literal(v))
                           for k, v in tags.items()]
            query_str += ' WHERE ' + ' AND '.join(tag_eq_list)

        self.logger.info('Executing DROP : %s on database: %s', query_str, database)
        
        # Building payload, headers, url
        payload = {'db': database, 'q': query_str}
        headers = {'Authorization': 'Token ' + self.username + ':' + self.password }
        url = 'http://' + self.host + ':' + str(self.port) + self.basepath

        response = requests.post(url, headers=headers, data=payload)
        jsonResponse = json.loads(response.text)
`
