### ISSUE TITLE
[Feature Request] Reload Configuration Online with Kill -HUP  or via API

### ISSUE THREAD

**Issue by toni-moreno** [toni-moreno/influxdb-srelay#7]
Will be interesting applying changes in the least impacting way to the service

**Comment by toni-moreno** [comment]
released on last version 0.4

**Comment by sbengo** [comment]
After some tests, we added a new rule and seems that incoming writes are not being matched on new rule.

After a restart, it worked as expected

**Comment by fredma** [comment]
Hi, 

I was hoping the reload would also work for any changes in the cluster members.

```
[[influxcluster]]
  # name = cluster id for route configs and logs
  name  = "read_cluster"
  # members = array of influxdb backends
  members = ["10.125.234.152", "10.125.224.53"]
```

 If I remove one member from the list or use an invalid IP, the log show the config has been reloaded. But when calling the api  /health/<cluster_name>, nothing changes.

```
2020/10/20 13:24:13 Received HUP signal
2020/10/20 13:24:13 Reloading Config File &config.Config{Influxdb:[]*config.InfluxDBBackend{(*config.InfluxDBBackend)(0xc000060ea0), (*config.InfluxDBBackend)(0xc000060f60), (*config.InfluxDBBackend)(0xc000061260)}, Influxcluster:[]*config.Influxcluster{(*config.Influxcluster)(0xc0000c4750), (*config.Influxcluster)(0xc0000c4870)}, HTTPConfig:[]*config.HTTPConfig{(*config.HTTPConfig)(0xc00009a630)}}
2020/10/20 13:24:13 Stopping relay ha-relay...
2020/10/20 13:24:13 Relay Reloaded OK
```

Would the reload work for every section in the config?

Thanks.

Fred
