### ISSUE TITLE
Keep readme in sync

### ISSUE THREAD

**Issue by zhangxin511** [toni-moreno/influxdb-srelay#8]
Thank you for developing this project. I understand it is still in beta version, but could we keep the changes in sync with read me? So we can know what are new in this repo vs veepee-moc/influxdb-relay

**Comment by toni-moreno** [comment]
Hi @zhangxin511 I've updated https://github.com/toni-moreno/influxdb-srelay/blob/master/README.md and added some config examples. Let me know if you can test this Smart-Relay and check if everything working ok

**Comment by toni-moreno** [comment]
@zhangxin511 as you said before this project is still in very early beta version. Any feedback will be wellcomed
